#!/usr/bin/env python2
""" test script to test filtering"""

if __name__=='__main__':
    import sys
    if len(sys.argv)<3:
        raise SystemExit, "usage: filtertest command filename_or_url"
    import wc, time
    from wc.proxy import proxy
    command = sys.argv[1]
    if command=='filter':
        data = open(sys.argv[2]).read()
        i = wc.filter.FILTER_RESPONSE_MODIFY
    elif command=='block':
        i = wc.filter.FILTER_REQUEST
        data = sys.argv[2]
    else:
        raise SystemExit, "unknown command"
    wc.configure(None, None)
    start = time.clock()
    attrs = proxy.initStateObjects()
    filtered = proxy.applyfilter(i, data, 'filter', attrs)
    filtered = filtered + proxy.applyfilter(i, '', 'finish', attrs)
    stop = time.clock()
    print filtered
    print "time: %.3f seconds" % (stop-start)
