.TH WCHEADERS 1 "6 November 2001"
.SH NAME
wcheaders \- display HTTP headers of a running webcleaner proxy
.SH SYNOPSIS
.B wcheaders
.SH DESCRIPTION
.LP
wcheaders is a graphical interface to display the HTTP headers
of all requests the local WebCleaner proxy handles.
.SH "SEE ALSO"
webcleaner(1)
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
