#!/usr/bin/env python
"""graphical HTTP header observation tool for webcleaner.

Developer note: you have to create() all windows which are created at
runtime. This is also a FAQ entry in the FOX documentation.
"""
# Copyright (C) 2001  Bastian Kleineidam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

import sys
if sys.version[:5] < "2.0":
    raise SystemExit, "This program requires Python 2.0 or later."

from wc.gui.ToolApp import ToolApp
from wc.gui.HeaderWindow import HeaderWindow

if __name__=='__main__':
    app = ToolApp("wcheaders")
    # create and run
    HeaderWindow(app)
    app.create()
    app.run()
