#!/usr/bin/python2.3
# -*- coding: iso-8859-1 -*-
"""graphical GUI configuration tool for webcleaner.

This is a nice graphical configuration tool for webcleaner. Because
it depends on some classes that come only with webcleaner, I do not
separate this tool from the webcleaner source.

Developer note: you have to create() all windows which are created at
runtime. This is also a FAQ entry in the FOX documentation.
"""
# Copyright (C) 2000,2001  Bastian Kleineidam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

__version__ = "$Revision$"[11:-2]
__date__    = "$Date$"[7:-2]

import sys, os
if sys.version[:5] < "2.3":
    raise SystemExit, "This program requires Python 2.3 or later."

try:
    from wc.gui.ConfWindow import ConfWindow
except ImportError:
    sys.path.insert(0, os.getcwd())
    from wc.gui.ConfWindow import ConfWindow
from wc.gui.ToolApp import ToolApp

if __name__=='__main__':
    app = ToolApp("webcleanerconf")
    # create and run
    ConfWindow(app)
    app.create()
    app.run()
