.TH WEBCLEANER.CONF 5 "3 January 2003"
.SH NAME
webcleaner.conf \- configuration file for webcleaner
.SH DESCRIPTION
.LP
\fIwebcleaner.conf\fP is the main configuration file for the
webcleaner proxy. The file has a custom XML format following
the Document Type Definition in the file webcleaner.dtd.

The following options are available:
.TP
\fBversion\fP
the configuration format version
.TP
\fBport\fP
the port number the WebCleaner Proxy is running on
.TP
\fBproxyuser\fP
the user name for proxy authentication
.TP
\fBproxypass\fP
the base64 encoded password for proxy authentication
.TP
\fBparentproxy\fP
the hostname of the HTTP parent proxy; leave empty to
not use a parent proxy
.TP
\fBparentproxyport\fP
the port number the parent proxy is running on
.TP
\fBparentproxyuser\fP
the user name for parent proxy authentication
.TP
\fBparentproxypass\fP
the base64 encoded password for parent proxy authentication
.TP
\fBshowerrors\fP
print detected html parse errors to stderr
.TP
\fBtimeout\fP
connection timeout in seconds
.TP
\fBgui\_theme\fP
web configuration gui theme selection
.TP
\fBnofilterhosts\fP
comma separated list of hosts for which filtering is disabled
.TP
\fBallowedhosts\fP
comma separated list of hosts which are allowed to use this proxy
.LP
The following filters are available:
.TP
\fBRewriter\fP
Parse the HTML stream and replace arbitrary tag constructs; filters
most advertising.
.TP
\fBBlocker\fP
Block specific urls; this replaces advert images and frames.
.TP
\fBBinaryCharFilter\fP
Replace some binary chars (espacially those illegal Microsoft
quote chars). You don't need this if you already enabled the Rewriter filter.
.TP
\fBHeader\fP
Replace, modify and add arbitrary HTTP headers.
.TP
\fBReplacer\fP
Replace text pieces in text data files (HTML, plain text, ...).
.TP
\fBGifImage\fP
Deanimate GIFs and remove GIF comments.
.TP
\fBCompress\fP
Compress documents with good compression ratio (HTML, WAV, ...).
.TP
\fBPicsHeader\fP
PICS filtering.
.TP
\fBImageReducer\fP
Reduce all images to low-quality jpegs. Useful for dialup users
with very low bandwidth.
.TP
\fBImageSize\fP
Filter images by size.
.SH EXAMPLE
 <?xml version="1.0"?>
 <!DOCTYPE webcleaner SYSTEM "webcleaner.dtd">
 <webcleaner 
  version="0.8"
  port="8000"
  parentproxy="squid.company.com"
  parentproxyport="3128"
  >
   <filter name="Rewriter"/>
   <filter name="Blocker"/>
   <filter name="Header"/>
   <filter name="Replacer"/>
   <filter name="GifImage"/>
  </webcleaner>
.SH "SEE ALSO"
webcleaner(1), webcleanerconf(1)
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
