.TH WEBCLEANERCONF 1 "22 November 2000"
.SH NAME
webcleanerconf \- configuration GUI for webcleaner
.SH SYNOPSIS
.B webcleanerconf
.SH DESCRIPTION
.LP
WebCleanerConf is a graphical interface to configure the proxy 
settings and filter settings of the HTTP proxy WebCleaner.
.SH "SEE ALSO"
webcleaner(1)
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
