#!/usr/bin/env python2.4
# -*- coding: iso-8859-1 -*-
import sys
import socket
import wc
import wc.configuration

def get_port_addr ():
    config = wc.configuration.init()
    port = config["port"]
    if config["bindaddress"]:
        host = config["bindaddress"]
    else:
        host = "127.0.0.1"
    return host, port

def main ():
    wc.initlog()
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect(get_port_addr())
        s.close()
    except:
        return 111
    return 0

if __name__ == '__main__':
    sys.exit(main())
