#define yy_create_buffer htmlop_create_buffer
#define yy_delete_buffer htmlop_delete_buffer
#define yy_scan_buffer htmlop_scan_buffer
#define yy_scan_string htmlop_scan_string
#define yy_scan_bytes htmlop_scan_bytes
#define yy_flex_debug htmlop_flex_debug
#define yy_init_buffer htmlop_init_buffer
#define yy_flush_buffer htmlop_flush_buffer
#define yy_load_buffer_state htmlop_load_buffer_state
#define yy_switch_to_buffer htmlop_switch_to_buffer
#define yyin htmlopin
#define yyleng htmlopleng
#define yylex htmloplex
#define yyout htmlopout
#define yyrestart htmloprestart
#define yytext htmloptext
#define yywrap htmlopwrap

#line 20 "htmlop.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
static yyconst short int yy_acclist[152] =
    {   0,
        9,    9,   44,    9,   43,    9,   43,    7,   43,   13,
       43,   13,   43,   11,   43,   11,   43,   14,   43,   16,
       43,   15,   43,   17,   43,   20,   43,   19,   43,   18,
       43,   17,   43,   24,   43,   23,   43,   24,   43,   24,
       43,   25,   43,   26,   43,   28,   43,   27,   43,   29,
       43,   31,   43,   30,   43,   32,   43,   34,   43,   43,
       32,   43,   35,   43,   38,   43,   37,   43,   35,   43,
       42,   43,   41,   43,   42,   43,   42,   43,    2,   43,
        4,   43,    9,    9,16385,    7,    6,    8,   13,   11,
       14,   16,   17,   17,   20,   19,   19,   24,   23,   24,

       24,   24,   24,   26,   28,   29,   31,   32,   34,   33,
       35,   38,   37,   37,   36,   42,   41,   42,   42,   42,
       42,    2, 8193,    9, 8193,    6,    8,   12,   24,   24,
       24,   24,   39,   42,   39,   39,   42,   40,   42,   40,
       40,   42,    5,    3,   21,   21,   22,   22,   39,   40,
       10
    } ;

static yyconst short int yy_accept[159] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    6,    8,
       10,   12,   14,   16,   18,   20,   22,   24,   26,   28,
       30,   32,   34,   36,   38,   40,   42,   44,   46,   48,
       50,   52,   54,   56,   58,   60,   61,   63,   65,   67,
       69,   71,   73,   75,   77,   79,   81,   83,   84,   86,
       87,   88,   88,   89,   90,   90,   91,   91,   92,   93,
       94,   95,   96,   97,   98,   98,   99,  100,  101,  101,
      102,  103,  103,  104,  105,  106,  107,  108,  109,  110,

      111,  112,  113,  114,  115,  116,  117,  118,  119,  119,
      120,  121,  121,  122,  123,  125,  126,  127,  127,  127,
      128,  128,  129,  129,  130,  130,  130,  131,  132,  132,
      132,  133,  135,  136,  136,  138,  140,  141,  141,  143,
      144,  145,  145,  146,  146,  147,  148,  148,  149,  150,
      151,  151,  151,  151,  151,  151,  152,  152
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    7,    8,    1,
        1,    1,    1,    1,    9,    1,   10,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   11,   12,
       13,   14,   15,    1,    1,    1,   16,    1,    1,    1,
        1,    1,   17,    1,    1,    1,    1,    1,    1,   18,
        1,   19,   20,   21,    1,    1,    1,    1,    1,    1,
        1,   22,    1,    1,    1,    1,    1,    1,   16,    1,

        1,    1,    1,    1,   17,    1,    1,    1,    1,    1,
        1,   18,    1,   19,   20,   21,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[23] =
    {   0,
        1,    2,    2,    2,    1,    1,    1,    1,    3,    1,
        4,    5,    6,    7,    8,    1,    1,    1,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[200] =
    {   0,
        0,    1,  188,  187,  183,  182,   12,   25,   38,   59,
       80,   93,  106,  119,  132,  145,  158,  172,  186,  200,
      214,  228,  242,  253,  179,  178,  191,    0,  264,  274,
        0,  176,    0,  174,    0,    0,  880,  161,  169,    7,
      880,    2,    0,   15,  288,  309,  880,    0,   18,  880,
        0,   28,  880,    0,   31,  880,  167,    0,  167,   34,
      165,    0,   41,  330,  351,    0,  880,    0,  372,   44,
      169,    0,   51,    0,  163,    0,  150,    0,   54,  143,
       46,  151,   62,   67,  160,    0,   72,  383,   71,  146,
      404,   70,  137,    0,   87,    0,  100,    0,  109,  880,

        0,  119,  112,  115,  880,    0,  122,  425,  121,  100,
      446,  120,   97,    0,  467,    0,  127,   91,   84,  135,
       73,  880,   69,  478,    0,  134,  491,  504,    0,  133,
      517,    0,  880,  144,    0,    0,  880,  136,    0,  880,
      880,   61,  880,  530,  145,  880,  551,  146,  147,  149,
       62,   49,   38,   11,    9,  880,  880,  573,  581,  589,
      597,  605,  613,  621,  629,  637,  645,  653,  661,  669,
      677,  685,  693,  701,  709,  716,  722,  730,  738,  746,
      754,  762,  770,  777,  783,  789,  797,  804,  808,  811,
      818,  825,  833,  841,  849,  856,  860,  866,  872

    } ;

static yyconst short int yy_def[200] =
    {   0,
      158,  158,  159,  159,  160,  160,  161,  161,  162,  162,
      163,  163,  164,  164,  165,  165,  166,  166,  167,  167,
      168,  168,  169,  169,  169,  169,  157,  170,  171,  157,
      172,  157,  173,  157,  174,  157,  157,  175,  176,  157,
      157,  175,  177,  157,  178,  179,  157,  180,  157,  157,
      181,  157,  157,  182,  157,  157,  182,  183,  184,  157,
      183,  185,  157,  186,  187,  188,  157,  170,  171,  157,
      189,  190,  157,  172,  191,  173,  157,  174,  157,  175,
      175,  176,  157,  157,  157,  177,  157,  178,  192,   88,
      179,  193,   91,  180,  157,  181,  157,  182,  157,  157,

      183,  184,  157,  157,  157,  185,  157,  186,  194,  108,
      187,  195,  111,  188,  170,  196,  157,  157,  190,  157,
      191,  157,  157,  177,  197,  192,   88,  177,  198,  193,
       91,  185,  157,  194,  108,  185,  157,  195,  111,  157,
      157,  157,  157,  192,  192,  157,  193,  193,  194,  195,
      157,  157,  157,  199,  199,  157,    0,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157

    } ;

static yyconst short int yy_nxt[903] =
    {   0,
      157,   79,   79,   79,   80,   85,   29,   29,   84,   84,
       84,   30,   30,   36,   36,   36,   87,   87,   87,   95,
       95,   95,  156,   81,  156,   37,   36,   36,   36,   97,
       97,   97,   99,   99,   99,  104,  104,  104,   37,   39,
       39,   39,  107,  107,  107,   70,   70,   70,   80,   85,
       40,   41,  120,  120,  120,   79,   79,   79,  154,   42,
       39,   39,   39,   84,   84,   84,  153,   81,   84,   84,
       84,   40,   41,   87,   87,   87,  125,  129,  152,  151,
       42,   44,   44,   44,  142,   45,  122,   46,   95,   95,
       95,  130,  126,   47,   44,   44,   44,  141,   45,  140,

       46,   97,   97,   97,  139,  135,   47,   49,   49,   49,
       99,   99,   99,  104,  104,  104,  104,  104,  104,   50,
       49,   49,   49,  107,  107,  107,  133,  137,  117,  117,
      117,  103,   50,   52,   52,   52,  120,  120,  120,  144,
      147,  138,  134,  150,  131,   53,   52,   52,   52,  149,
      125,  127,  133,  129,  130,  126,  137,  138,   53,   55,
       55,   55,   80,   83,   81,  134,  126,  130,  134,  123,
      138,   56,   57,   55,   55,   55,  122,  118,  105,  103,
      100,   83,   81,   77,   75,   56,   57,   59,   59,   59,
      157,   67,   67,   34,   34,   32,   32,  157,   60,   56,

       61,   59,   59,   59,  157,  157,  157,  157,  157,  157,
      157,  157,   60,   56,   61,   63,   63,   63,  157,   64,
      157,   65,  157,  157,  157,  157,  157,   56,   56,   63,
       63,   63,  157,   64,  157,   65,  157,  157,  157,  157,
      157,   56,   56,   66,   66,   66,  157,  157,  157,  157,
      157,  157,   66,   66,   66,   66,   66,  157,  157,  157,
      157,  157,  157,   66,   66,   68,   68,   68,  157,  157,
      157,  157,  157,  157,   68,   70,   70,   70,   71,  157,
      157,  157,  157,   72,  157,  157,  157,  157,   73,   89,
       89,   89,  157,   86,  157,  157,  157,  157,  157,  157,

      157,   89,  157,  157,  157,  157,  157,  157,  157,   90,
       92,   92,   92,  157,  157,  157,   86,  157,  157,  157,
      157,  157,   92,  157,  157,  157,  157,  157,  157,  157,
       93,  109,  109,  109,  157,  106,  157,  157,  157,  157,
      157,  157,  157,  109,  109,  157,  157,  157,  157,  157,
      157,  110,  112,  112,  112,  157,  157,  157,  106,  157,
      157,  157,  157,  157,  112,  112,  157,  157,  157,  157,
      157,  157,  113,  115,  115,  115,  157,  157,  157,  157,
      157,  157,  115,  116,   89,   89,   89,  157,  124,  157,
      157,  157,  157,  157,  157,  157,   89,  157,  157,  157,

      157,  157,  157,  157,   90,   92,   92,   92,  157,  157,
      157,  128,  157,  157,  157,  157,  157,   92,  157,  157,
      157,  157,  157,  157,  157,   93,  109,  109,  109,  157,
      132,  157,  157,  157,  157,  157,  157,  157,  109,  109,
      157,  157,  157,  157,  157,  157,  110,  112,  112,  112,
      157,  157,  157,  136,  157,  157,  157,  157,  157,  112,
      112,  157,  157,  157,  157,  157,  157,  113,  115,  115,
      115,  157,  157,  157,  157,  157,  157,  115,  116,  143,
      143,  143,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  143,  145,  145,  145,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  145,  146,  146,  146,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  146,  148,  148,
      148,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      148,  145,  145,  145,  157,  125,  157,  157,  157,  157,
      157,  157,  157,  145,  157,  157,  157,  157,  157,  157,
      157,  126,  148,  148,  148,  157,  157,  157,  129,  157,
      157,  157,  157,  157,  148,  157,  157,  157,  157,  157,
      157,  157,  130,   28,   28,   28,   28,   28,   28,   28,
       28,   31,   31,   31,   31,   31,   31,   31,   31,   33,
       33,   33,   33,   33,   33,   33,   33,   35,   35,   35,

       35,   35,   35,   35,   35,   38,   38,   38,   38,   38,
       38,   38,   38,   43,   43,   43,   43,   43,   43,   43,
       43,   48,   48,   48,   48,   48,   48,   48,   48,   51,
       51,   51,   51,   51,   51,   51,   51,   54,   54,   54,
       54,   54,   54,   54,   54,   58,   58,   58,   58,   58,
       58,   58,   58,   62,   62,   62,   62,   62,   62,   62,
       62,   56,   56,   56,   56,   56,   56,   56,   56,   68,
       68,   68,   68,  157,   68,   68,   68,   69,   69,   69,
       69,  157,   69,   69,   69,   74,   74,  157,   74,   74,
       74,   74,   74,   76,   76,   76,   76,  157,   76,   76,

       76,   78,  157,   78,   78,   78,   78,  157,   78,   80,
      157,   80,   80,   80,  157,  157,   80,   82,  157,  157,
      157,   82,   86,  157,   86,   86,   86,   86,  157,   86,
       88,   88,   88,   88,   88,   88,   88,   88,   91,   91,
       91,   91,   91,   91,   91,   91,   94,  157,   94,   94,
       94,   94,  157,   94,   96,  157,   96,   96,   96,   96,
      157,   96,   98,  157,   98,   98,   98,   98,  157,   98,
      101,  157,  101,  101,  101,  157,  157,  101,  102,  157,
      157,  157,  102,  106,  157,  106,  106,  106,  106,  108,
      108,  108,  108,  108,  108,  108,  108,  111,  111,  111,

      111,  111,  111,  111,  111,  114,  157,  114,  114,  117,
      117,  119,  119,  119,  119,  119,  119,  157,  119,  121,
      157,  157,  157,  157,  121,   89,   89,   89,   89,   89,
       89,   89,   89,   92,   92,   92,   92,   92,   92,   92,
       92,  109,  109,  109,  109,  109,  109,  109,  109,  112,
      112,  112,  112,  112,  112,  112,  112,  116,  157,  116,
      116,  143,  157,  157,  157,  157,  143,  146,  157,  157,
      157,  157,  146,  155,  157,  157,  157,  157,  155,   27,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      157,  157
    } ;

static yyconst short int yy_chk[903] =
    {   0,
        0,   36,   36,   36,   42,   42,    1,    2,   40,   40,
       40,    1,    2,    7,    7,    7,   44,   44,   44,   49,
       49,   49,  155,   42,  154,    7,    8,    8,    8,   52,
       52,   52,   55,   55,   55,   60,   60,   60,    8,    9,
        9,    9,   63,   63,   63,   70,   70,   70,   81,   81,
        9,    9,   73,   73,   73,   79,   79,   79,  153,    9,
       10,   10,   10,   83,   83,   83,  152,   81,   84,   84,
       84,   10,   10,   87,   87,   87,   89,   92,  151,  142,
       10,   11,   11,   11,  123,   11,  121,   11,   95,   95,
       95,   92,   89,   11,   12,   12,   12,  119,   12,  118,

       12,   97,   97,   97,  113,  110,   12,   13,   13,   13,
       99,   99,   99,  103,  103,  103,  104,  104,  104,   13,
       14,   14,   14,  107,  107,  107,  109,  112,  117,  117,
      117,  102,   14,   15,   15,   15,  120,  120,  120,  126,
      130,  112,  109,  138,   93,   15,   16,   16,   16,  134,
      145,   90,  149,  148,  130,  126,  150,  138,   16,   17,
       17,   17,   85,   82,   80,  134,  145,  148,  149,   77,
      150,   17,   17,   18,   18,   18,   75,   71,   61,   59,
       57,   39,   38,   34,   32,   18,   18,   19,   19,   19,
       27,   26,   25,    6,    5,    4,    3,    0,   19,   19,

       19,   20,   20,   20,    0,    0,    0,    0,    0,    0,
        0,    0,   20,   20,   20,   21,   21,   21,    0,   21,
        0,   21,    0,    0,    0,    0,    0,   21,   21,   22,
       22,   22,    0,   22,    0,   22,    0,    0,    0,    0,
        0,   22,   22,   23,   23,   23,    0,    0,    0,    0,
        0,    0,   23,   23,   24,   24,   24,    0,    0,    0,
        0,    0,    0,   24,   24,   29,   29,   29,    0,    0,
        0,    0,    0,    0,   29,   30,   30,   30,   30,    0,
        0,    0,    0,   30,    0,    0,    0,    0,   30,   45,
       45,   45,    0,   45,    0,    0,    0,    0,    0,    0,

        0,   45,    0,    0,    0,    0,    0,    0,    0,   45,
       46,   46,   46,    0,    0,    0,   46,    0,    0,    0,
        0,    0,   46,    0,    0,    0,    0,    0,    0,    0,
       46,   64,   64,   64,    0,   64,    0,    0,    0,    0,
        0,    0,    0,   64,   64,    0,    0,    0,    0,    0,
        0,   64,   65,   65,   65,    0,    0,    0,   65,    0,
        0,    0,    0,    0,   65,   65,    0,    0,    0,    0,
        0,    0,   65,   69,   69,   69,    0,    0,    0,    0,
        0,    0,   69,   69,   88,   88,   88,    0,   88,    0,
        0,    0,    0,    0,    0,    0,   88,    0,    0,    0,

        0,    0,    0,    0,   88,   91,   91,   91,    0,    0,
        0,   91,    0,    0,    0,    0,    0,   91,    0,    0,
        0,    0,    0,    0,    0,   91,  108,  108,  108,    0,
      108,    0,    0,    0,    0,    0,    0,    0,  108,  108,
        0,    0,    0,    0,    0,    0,  108,  111,  111,  111,
        0,    0,    0,  111,    0,    0,    0,    0,    0,  111,
      111,    0,    0,    0,    0,    0,    0,  111,  115,  115,
      115,    0,    0,    0,    0,    0,    0,  115,  115,  124,
      124,  124,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  124,  127,  127,  127,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  127,  128,  128,  128,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  128,  131,  131,
      131,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      131,  144,  144,  144,    0,  144,    0,    0,    0,    0,
        0,    0,    0,  144,    0,    0,    0,    0,    0,    0,
        0,  144,  147,  147,  147,    0,    0,    0,  147,    0,
        0,    0,    0,    0,  147,    0,    0,    0,    0,    0,
        0,    0,  147,  158,  158,  158,  158,  158,  158,  158,
      158,  159,  159,  159,  159,  159,  159,  159,  159,  160,
      160,  160,  160,  160,  160,  160,  160,  161,  161,  161,

      161,  161,  161,  161,  161,  162,  162,  162,  162,  162,
      162,  162,  162,  163,  163,  163,  163,  163,  163,  163,
      163,  164,  164,  164,  164,  164,  164,  164,  164,  165,
      165,  165,  165,  165,  165,  165,  165,  166,  166,  166,
      166,  166,  166,  166,  166,  167,  167,  167,  167,  167,
      167,  167,  167,  168,  168,  168,  168,  168,  168,  168,
      168,  169,  169,  169,  169,  169,  169,  169,  169,  170,
      170,  170,  170,    0,  170,  170,  170,  171,  171,  171,
      171,    0,  171,  171,  171,  172,  172,    0,  172,  172,
      172,  172,  172,  173,  173,  173,  173,    0,  173,  173,

      173,  174,    0,  174,  174,  174,  174,    0,  174,  175,
        0,  175,  175,  175,    0,    0,  175,  176,    0,    0,
        0,  176,  177,    0,  177,  177,  177,  177,    0,  177,
      178,  178,  178,  178,  178,  178,  178,  178,  179,  179,
      179,  179,  179,  179,  179,  179,  180,    0,  180,  180,
      180,  180,    0,  180,  181,    0,  181,  181,  181,  181,
        0,  181,  182,    0,  182,  182,  182,  182,    0,  182,
      183,    0,  183,  183,  183,    0,    0,  183,  184,    0,
        0,    0,  184,  185,    0,  185,  185,  185,  185,  186,
      186,  186,  186,  186,  186,  186,  186,  187,  187,  187,

      187,  187,  187,  187,  187,  188,    0,  188,  188,  189,
      189,  190,  190,  190,  190,  190,  190,    0,  190,  191,
        0,    0,    0,    0,  191,  192,  192,  192,  192,  192,
      192,  192,  192,  193,  193,  193,  193,  193,  193,  193,
      193,  194,  194,  194,  194,  194,  194,  194,  194,  195,
      195,  195,  195,  195,  195,  195,  195,  196,    0,  196,
      196,  197,    0,    0,    0,    0,  197,  198,    0,    0,
        0,    0,  198,  199,    0,    0,    0,    0,  199,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      157,  157
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "htmlop.l"
#define INITIAL 0
#line 2 "htmlop.l"

/* lhtml.l: source code for libhtmlparse parser
   Mooneer Salem <mooneer@translator.cx> 

   used and adapted for WebCleaner by
   Bastian Kleineidam <calvin@users.sourceforge.net>
   I ripped some of the code structure from sgmlop.c parser,
   which is written by Fredrik Lundh <fredrik@pythonware.com>
*/

#include <string.h>
#include <Python.h>

/* require Python >= 2.0 */
#ifndef PY_VERSION_HEX
#error please install Python >= 2.0
#endif

#if PY_VERSION_HEX < 0x02000000
#error please install Python >= 2.0
#endif

#define LHTML_EOF -128
#define CFREE(a) PyMem_Del(a); a=NULL
#define PFREE(a) Py_DECREF(a); a=NULL
#define XCFREE(a) if (a) { PyMem_Del(a); a=NULL; }
#define XPFREE(a) if (a) { Py_DECREF(a); a=NULL; }
#define yyterminate() return YY_NULL
/*
#define DEBUG
*/
#ifdef DEBUG
#define _debug fprintf(stderr, "state %d yytext %s\n", YYSTATE, yytext)
#else
#define _debug
#endif

/* on Linux: strncasecmp
   on Windows: StrCmpIN ?
   on other: ??
   
   so, here the glibc 2.2.4 code
*/
int my_strncasecmp(const char* s1, const char* s2, int n) {
    const unsigned char* p1 = (const unsigned char*) s1;
    const unsigned char* p2 = (const unsigned char*) s2;
    unsigned char c1, c2;

    if (p1 == p2 || n == 0)
        return 0;

    do {
        c1 = tolower(*p1++);
        c2 = tolower(*p2++);
        if (c1 == '\0' || c1 != c2)
	    return c1 - c2;
    } while (--n > 0);

    return c1 - c2;
}

int htmlopwrap (void) {
    return 1;
}

/* parser type definition */

typedef struct {
    PyObject_HEAD

    /* flex state */
    int state;
    
    /* temporary values for parsing */
    char* tag;
    char* paramname;
    PyObject* params;

    /* callbacks */
    PyObject* handle_starttag;
    PyObject* handle_endtag;
    PyObject* handle_decl;
    PyObject* handle_xmldecl;
    PyObject* handle_ref;
    PyObject* handle_data;
    PyObject* handle_comment;

} parser_object;

staticforward PyTypeObject parser_type;

/* pass the parser object to the scanner */
#define YY_DECL int html_scan (parser_object* self)

#define COMMENT 1

#define SCRIPT 2

#define STARTTAG 3

#define PARAM 4

#define PARAM2 5

#define DECLTAG 6

#define DPARAM 7

#define XMLTAG 8

#define XPARAM 9

#define XPARAM2 10

#define ENTITY 11

#define ENDTAG 12

#line 793 "htmlop.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 113 "htmlop.l"


#line 947 "htmlop.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 158 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 880 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case YY_STATE_EOF(INITIAL):
#line 115 "htmlop.l"
{
    _debug;
    return LHTML_EOF;
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 120 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_ref, "s", yytext+1);
    BEGIN(ENTITY);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 126 "htmlop.l"
{
    char *tmp = yytext + strlen(yytext) - 1;
    int i;
    _debug;
    for (i = strlen(tmp) - 1; i >= 0; i--) {
        if (*(tmp+i) != ';') {
	    unput(*(tmp+i));
	}
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 138 "htmlop.l"
{
    /* strip tag chars and whitespace */
    int i=2, j;
    _debug;
    while (*(yytext+i) != '\0' && isspace(*(yytext+i))) i++;
    j=i;
    while (*(yytext+j) != '\0' && !isspace(*(yytext+j))) j++;
    PyObject_CallFunction(self->handle_endtag, "s#", yytext+i, j-i);
    BEGIN(ENDTAG);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 149 "htmlop.l"
{
    _debug;
    BEGIN(INITIAL);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 154 "htmlop.l"
{
    _debug;
    self->tag = PyMem_Resize(self->tag, char, 1);
    self->tag[0] = '\0';
    BEGIN(COMMENT);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 161 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(DECLTAG);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 167 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(STARTTAG);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 173 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(XMLTAG);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 179 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_data, "s", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 184 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_endtag, "s", "script");
    BEGIN(INITIAL);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 190 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_data, "s", yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 195 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_comment, "s", self->tag);
    CFREE(self->tag);
    BEGIN(INITIAL);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 202 "htmlop.l"
{
    int len = strlen(self->tag);
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len+strlen(yytext)] = '\0';
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 210 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 220 "htmlop.l"
{
    int n;
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    n = strlen(self->tag);
    if (n==6 && my_strncasecmp(self->tag, "script", n)==0) {
        BEGIN(SCRIPT);
    }
    else {
        BEGIN(INITIAL);
    }
    CFREE(self->tag);
    PFREE(self->params);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 246 "htmlop.l"
{
    _debug;
    BEGIN(PARAM);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 251 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 258 "htmlop.l"
{
    int n;
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    n = strlen(self->tag);
    if (n>=6 && my_strncasecmp(self->tag, "script", n)==0) {
        BEGIN(SCRIPT);
    }
    else {
        BEGIN(INITIAL);
    }
    CFREE(self->tag);
    PFREE(self->params);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 284 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = PyMem_New(char, 1);
        self->paramname[0] = '\0';
    }
    BEGIN(PARAM2);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 294 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 21:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 301 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 22:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 308 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 315 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 321 "htmlop.l"
{
    int i=0;
    int j=strlen(yytext)-1;
    _debug;
    /* strip optional quotes, for things like <a b="c> */
    if (yytext[i]=='\'' || yytext[i]=='"') i++;
    if (yytext[j]=='\'' || yytext[j]=='"') j--;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+i, j-i+1));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 333 "htmlop.l"
{
    int n;
    _debug;
    /* this occurs with <a b=> */
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    n = strlen(self->tag);
    if (n>=6 && my_strncasecmp(self->tag, "script", n)==0) {
        BEGIN(SCRIPT);
    }
    else {
        BEGIN(INITIAL);
    }
    CFREE(self->tag);
    PFREE(self->params);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 358 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 368 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 380 "htmlop.l"
{
    _debug;
    BEGIN(DPARAM);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 385 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 392 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 404 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 411 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 421 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    PyObject_CallFunction(self->handle_xmldecl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 433 "htmlop.l"
{
    _debug;
    BEGIN(XPARAM);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 438 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 445 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    PyObject_CallFunction(self->handle_xmldecl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 457 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = PyMem_New(char, 1);
        self->paramname[0] = '\0';
    }
    BEGIN(XPARAM2);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 467 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 474 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 481 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 488 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 494 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext, strlen(yytext)-1));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 501 "htmlop.l"
ECHO;
	YY_BREAK
#line 1579 "htmlop.c"
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(SCRIPT):
			case YY_STATE_EOF(STARTTAG):
			case YY_STATE_EOF(PARAM):
			case YY_STATE_EOF(PARAM2):
			case YY_STATE_EOF(DECLTAG):
			case YY_STATE_EOF(DPARAM):
			case YY_STATE_EOF(XMLTAG):
			case YY_STATE_EOF(XPARAM):
			case YY_STATE_EOF(XPARAM2):
			case YY_STATE_EOF(ENTITY):
			case YY_STATE_EOF(ENDTAG):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 158 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 158 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 157);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 501 "htmlop.l"


/* create parser */
static PyObject* htmlop_parser(PyObject* self, PyObject* args) {
    PyObject* item;
    parser_object* p;
    if (!PyArg_ParseTuple(args, "O", &item)) {
	return NULL;
    }

    if (!(p=PyObject_NEW(parser_object, &parser_type))) {
	return NULL;
    }

    p->state = 0;
    p->tag = NULL;
    p->paramname = NULL;
    p->params = NULL;

    /* register callbacks */
    p->handle_starttag = PyObject_GetAttrString(item, "handle_starttag");
    p->handle_endtag = PyObject_GetAttrString(item, "handle_endtag");
    p->handle_decl = PyObject_GetAttrString(item, "handle_decl");
    p->handle_xmldecl = PyObject_GetAttrString(item, "handle_xmldecl");
    p->handle_ref = PyObject_GetAttrString(item, "handle_ref");
    p->handle_data = PyObject_GetAttrString(item, "handle_data");
    p->handle_comment = PyObject_GetAttrString(item, "handle_comment");
    /* dont PyErr_Clear(); because we dont accept missing callbacks! */
    return (PyObject*) p;
}


static void parser_dealloc(parser_object* self)
{
    if (self->tag) {
       PyMem_Del(self->tag);
    }
    if (self->paramname) {
        PyMem_Del(self->paramname);
    }
    Py_XDECREF(self->params);
    Py_DECREF(self->handle_starttag);
    Py_DECREF(self->handle_endtag);
    Py_DECREF(self->handle_decl);
    Py_DECREF(self->handle_xmldecl);
    Py_DECREF(self->handle_ref);
    Py_DECREF(self->handle_data);
    Py_DECREF(self->handle_comment);
    PyMem_DEL(self);
}


static PyObject* parser_flush(parser_object* self, PyObject* args) {
    /* flush parser buffers */
    if (!PyArg_ParseTuple(args, "")) {
        return NULL;
    }
    /*
       Because we did not store previous data we have to look at 
       the current state and the temp vars.
    */
    switch(self->state) {
    case STARTTAG:
    case PARAM:
    case PARAM2:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        if (!self->params) {
            self->params = PyList_New(0);
        }
        if (self->tag[strlen(self->tag)-1]=='/') {
            /* no parameters allowed for this construct */
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
            PyObject_CallFunction(self->handle_endtag, "s", self->tag);
        }
        else {
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
        }
	break;
    case DECLTAG:
    case DPARAM:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
        break;
    case XMLTAG:
    case XPARAM:
    case XPARAM2:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        if (!self->params) {
            self->params = PyList_New(0);
        }
        PyObject_CallFunction(self->handle_xmldecl, "sO", self->tag, self->params);
        break;
    case COMMENT:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_comment, "s", self->tag);
	break;
    default:
        break;
    }
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_feed(parser_object* self, PyObject* args) {
    /* feed a chunk of data to the parser */
    char* s;
    int slen;
    YY_BUFFER_STATE bufstate;
    if (!PyArg_ParseTuple(args, "t#", &s, &slen)) {
	return NULL;
    }
    bufstate = htmlop_scan_bytes(s, slen);
    if (self->state != YYSTATE) {
        BEGIN(self->state);
    }
    html_scan(self);
    self->state = YYSTATE;
    htmlop_delete_buffer(bufstate);
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_reset(parser_object* self, PyObject* args) {
    if (!PyArg_ParseTuple(args, "")) {
	return NULL;
    }
    XCFREE(self->tag);
    XCFREE(self->paramname);
    XPFREE(self->params);
    self->state = INITIAL;
    Py_INCREF(Py_None);
    return Py_None;
}


/* type interface */

static PyMethodDef parser_methods[] = {
    /* incremental parsing */
    {"feed",  (PyCFunction) parser_feed, METH_VARARGS},
    /* reset the parser (no flushing) */
    {"reset", (PyCFunction) parser_reset, METH_VARARGS},
    /* flush the parser buffers */
    {"flush", (PyCFunction) parser_flush, METH_VARARGS},
    {NULL, NULL}
};


static PyObject* parser_getattr(parser_object* self, char* name) {
    return Py_FindMethod(parser_methods, (PyObject*) self, name);
}


statichere PyTypeObject parser_type = {
    PyObject_HEAD_INIT(NULL)
    0, /* ob_size */
    "parser", /* tp_name */
    sizeof(parser_object), /* tp_size */
    0, /* tp_itemsize */
    /* methods */
    (destructor)parser_dealloc, /* tp_dealloc */
    0, /* tp_print */
    (getattrfunc)parser_getattr, /* tp_getattr */
    0 /* tp_setattr */
};


/* python module interface */

static PyMethodDef htmlop_methods[] = {
    {"parser", htmlop_parser, METH_VARARGS},
    {NULL, NULL}
};


/* initialization of the htmlop module */

void inithtmlop(void) {
    Py_InitModule("htmlop", htmlop_methods);
}
