#define yy_create_buffer htmlop_create_buffer
#define yy_delete_buffer htmlop_delete_buffer
#define yy_scan_buffer htmlop_scan_buffer
#define yy_scan_string htmlop_scan_string
#define yy_scan_bytes htmlop_scan_bytes
#define yy_flex_debug htmlop_flex_debug
#define yy_init_buffer htmlop_init_buffer
#define yy_flush_buffer htmlop_flush_buffer
#define yy_load_buffer_state htmlop_load_buffer_state
#define yy_switch_to_buffer htmlop_switch_to_buffer
#define yyin htmlopin
#define yyleng htmlopleng
#define yylex htmloplex
#define yyout htmlopout
#define yyrestart htmloprestart
#define yytext htmloptext
#define yywrap htmlopwrap

#line 20 "htmlop.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
static yyconst short int yy_acclist[170] =
    {   0,
        9,    9,   47,    9,   46,    9,   46,    7,   46,   11,
       46,   11,   46,   12,   46,   14,   46,   13,   46,   15,
       46,   18,   46,   17,   46,   16,   46,   22,   46,   21,
       46,   22,   46,   22,   46,   23,   46,   24,   46,   26,
       46,   25,   46,   27,   46,   30,   46,   29,   46,   28,
       46,   34,   46,   33,   46,   34,   46,   34,   46,   46,
       35,   46,   37,   46,   35,   46,   38,   46,   41,   46,
       40,   46,   38,   46,   45,   46,   44,   46,   45,   46,
       45,   46,    2,   46,    4,   46,    9,    9,16385,    7,
        6,    8,   11,   12,   14,   15,   18,   17,   22,   21,

       22,   22,   22,   22,   24,   26,   27,   30,   29,   34,
       33,   34,   34,   34,   34,   35,   37,   36,   38,   41,
       40,   39,   45,   44,   45,   45,   45,   45,    2, 8193,
        9, 8193,    6,    8,   10,   22,   22,   22,   22,   31,
       34,   31,   31,   34,   32,   34,   32,   32,   34,   42,
       45,   42,   42,   45,   43,   45,   43,   43,   45,    5,
        3,   19,   19,   20,   20,   31,   32,   42,   43
    } ;

static yyconst short int yy_accept[166] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    6,    8,
       10,   12,   14,   16,   18,   20,   22,   24,   26,   28,
       30,   32,   34,   36,   38,   40,   42,   44,   46,   48,
       50,   52,   54,   56,   58,   60,   61,   63,   65,   67,
       69,   71,   73,   75,   77,   79,   81,   83,   85,   87,
       88,   90,   91,   92,   92,   93,   94,   94,   95,   96,
       97,   98,   99,  100,  101,  102,  102,  103,  104,  104,
      105,  106,  107,  108,  109,  110,  111,  112,  113,  113,

      114,  115,  115,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  126,  127,  128,  128,  129,  130,
      132,  133,  134,  134,  134,  135,  135,  136,  137,  137,
      137,  138,  139,  139,  139,  140,  142,  143,  143,  145,
      147,  148,  148,  150,  152,  153,  153,  155,  157,  158,
      158,  160,  161,  162,  163,  163,  164,  165,  165,  166,
      167,  168,  169,  170,  170
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    4,    1,    1,    1,    5,    6,    1,
        1,    1,    1,    1,    7,    1,    8,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       11,   12,   13,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   14,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[15] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    4,    5,
        6,    7,    8,    1
    } ;

static yyconst short int yy_base[204] =
    {   0,
        0,    1,  151,  150,    0,    1,   12,   23,   34,   45,
        5,    6,   56,   67,   78,   89,  100,  112,  124,  136,
      148,  160,  172,  181,  144,  143,  153,    0,    7,  190,
        0,  144,    0,  144,  706,    0,   17,  706,  706,    0,
      143,  202,  215,  706,    0,  142,  706,    0,   18,  706,
      706,    0,  141,  228,  241,  706,    0,  140,  129,    0,
       19,  706,  128,    0,  137,  254,  267,    0,  706,    0,
      280,  132,   20,    0,  131,    0,   29,    0,  130,    0,
       31,  706,    0,  129,  289,   39,  126,  302,   31,  123,
        0,  121,    0,   37,  706,    0,  120,  315,   40,  117,

      328,   46,  113,    0,  104,  706,    0,   48,  706,  706,
        0,   81,  341,   51,   70,  354,   50,   64,    0,  367,
        0,   30,   19,    3,    2,   59,  706,   60,   61,   62,
       73,   75,   84,   75,   86,    0,  706,   90,    0,    0,
      706,   86,    0,    0,  706,   93,    0,    0,  706,   97,
        0,  706,  706,  706,  376,   95,  706,  389,  102,  101,
      104,  113,  114,  706,  403,  411,  419,  427,  435,  443,
      451,  459,  467,  475,  483,  491,  499,  507,  515,  523,
      531,  539,  547,  555,  563,  571,  579,  587,  595,  603,
      611,  619,  625,  633,  640,  645,  653,  661,  669,  677,

      685,  693,  700
    } ;

static yyconst short int yy_def[204] =
    {   0,
      165,  165,  166,  166,  167,  167,  168,  168,  169,  169,
      170,  170,  171,  171,  172,  172,  173,  173,  174,  174,
      175,  175,  176,  176,  176,  176,  164,  177,  178,  164,
      179,  164,  180,  164,  164,  181,  164,  164,  164,  182,
      164,  183,  184,  164,  185,  164,  164,  186,  164,  164,
      164,  187,  164,  188,  189,  164,  190,  164,  190,  191,
      164,  164,  191,  192,  164,  193,  194,  195,  164,  177,
      178,  164,  164,  196,  164,  179,  164,  180,  164,  181,
      164,  164,  182,  164,  183,  197,   85,  184,  198,   88,
      185,  164,  186,  164,  164,  187,  164,  188,  199,   98,

      189,  200,  101,  190,  164,  164,  191,  164,  164,  164,
      192,  164,  193,  201,  113,  194,  202,  116,  195,  177,
      203,  164,  164,  196,  164,  164,  164,  182,  164,  197,
       85,  182,  164,  198,   88,  187,  164,  199,   98,  187,
      164,  200,  101,  192,  164,  201,  113,  192,  164,  202,
      116,  164,  164,  164,  197,  197,  164,  198,  198,  199,
      200,  201,  202,    0,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164
    } ;

static yyconst short int yy_nxt[721] =
    {   0,
      164,   34,   34,  125,   29,   29,   46,   46,   70,   30,
       30,   35,   35,   37,  153,   70,   47,   47,   81,   94,
      108,  122,   38,   39,   37,  152,  123,   82,   95,  109,
      126,  122,   81,   38,   39,   41,  133,   42,   94,   43,
      127,   82,  129,  137,  134,   44,   41,   95,   42,  108,
       43,  141,  130,  138,  145,  149,   44,   49,  109,  142,
      126,  154,  154,  150,  146,  155,   50,   51,   49,  151,
      127,  154,  154,  147,  156,  130,  157,   50,   51,   53,
      158,   54,  112,   55,  156,  157,  157,  159,  134,   56,
       53,  161,   54,  160,   55,  157,  162,  159,  129,  142,

       56,   58,  163,  138,  137,  105,  146,  133,  130,  141,
      150,   56,   59,   58,  138,  134,  145,  142,  143,  149,
      139,   97,   92,   56,   59,   61,  146,  150,  135,  131,
       84,   79,  125,   72,   62,   56,   63,   61,  112,  110,
      106,  105,   97,   92,   84,   79,   62,   56,   63,   65,
       77,   66,  164,   67,   69,   69,   32,   32,  164,   56,
       56,   65,  164,   66,  164,   67,  164,  164,  164,  164,
      164,   56,   56,   68,  164,  164,  164,  164,  164,  164,
       68,   68,   68,  164,  164,  164,  164,  164,  164,   68,
       68,   72,   73,  164,  164,  164,  164,   74,  164,  164,

      164,  164,   75,   86,  164,   83,  164,  164,  164,  164,
      164,  164,  164,   86,  164,   87,   89,  164,  164,  164,
       83,  164,  164,  164,  164,  164,   89,  164,   90,   99,
      164,   96,  164,  164,  164,  164,  164,  164,  164,   99,
      164,  100,  102,  164,  164,  164,   96,  164,  164,  164,
      164,  164,  102,  164,  103,  114,  164,  111,  164,  164,
      164,  164,  164,  164,  164,  114,  114,  115,  117,  164,
      164,  164,  111,  164,  164,  164,  164,  164,  117,  117,
      118,  120,  164,  164,  164,  164,  164,  164,  120,  121,
       86,  164,  128,  164,  164,  164,  164,  164,  164,  164,

       86,  164,   87,   89,  164,  164,  164,  132,  164,  164,
      164,  164,  164,   89,  164,   90,   99,  164,  136,  164,
      164,  164,  164,  164,  164,  164,   99,  164,  100,  102,
      164,  164,  164,  140,  164,  164,  164,  164,  164,  102,
      164,  103,  114,  164,  144,  164,  164,  164,  164,  164,
      164,  164,  114,  114,  115,  117,  164,  164,  164,  148,
      164,  164,  164,  164,  164,  117,  117,  118,  120,  164,
      164,  164,  164,  164,  164,  120,  121,  156,  164,  129,
      164,  164,  164,  164,  164,  164,  164,  156,  164,  130,
      159,  164,  164,  164,  133,  164,  164,  164,  164,  164,

      159,  164,  134,   28,   28,   28,   28,   28,   28,   28,
       28,   31,   31,   31,   31,   31,   31,   31,   31,   33,
       33,   33,   33,   33,   33,   33,   33,   36,   36,   36,
       36,   36,   36,   36,   36,   40,   40,   40,   40,   40,
       40,   40,   40,   45,   45,   45,   45,   45,   45,   45,
       45,   48,   48,   48,   48,   48,   48,   48,   48,   52,
       52,   52,   52,   52,   52,   52,   52,   57,   57,   57,
       57,   57,   57,   57,   57,   60,   60,   60,   60,   60,
       60,   60,   60,   64,   64,   64,   64,   64,   64,   64,
       64,   56,   56,   56,   56,   56,   56,   56,   56,   70,

       70,   70,   70,  164,   70,   70,   70,   71,   71,   71,
       71,  164,   71,   71,   71,   76,   76,  164,   76,   76,
       76,   76,   76,   78,  164,   78,   78,   78,   78,  164,
       78,   80,  164,   80,   80,   80,  164,  164,   80,   83,
      164,   83,   83,   83,   83,  164,   83,   85,   85,   85,
       85,   85,   85,   85,   85,   88,   88,   88,   88,   88,
       88,   88,   88,   91,  164,   91,   91,   91,   91,  164,
       91,   93,  164,   93,   93,   93,  164,  164,   93,   96,
      164,   96,   96,   96,   96,  164,   96,   98,   98,   98,
       98,   98,   98,   98,   98,  101,  101,  101,  101,  101,

      101,  101,  101,  104,  164,  104,  104,  104,  104,  164,
      104,  107,  164,  107,  107,  107,  164,  164,  107,  111,
      164,  111,  111,  111,  111,  113,  113,  113,  113,  113,
      113,  113,  113,  116,  116,  116,  116,  116,  116,  116,
      116,  119,  164,  119,  119,  124,  124,  124,  124,  124,
      124,  164,  124,   86,   86,   86,   86,   86,   86,   86,
       86,   89,   89,   89,   89,   89,   89,   89,   89,   99,
       99,   99,   99,   99,   99,   99,   99,  102,  102,  102,
      102,  102,  102,  102,  102,  114,  114,  114,  114,  114,
      114,  114,  114,  117,  117,  117,  117,  117,  117,  117,

      117,  121,  164,  121,  121,   27,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yyconst short int yy_chk[721] =
    {   0,
        0,    5,    6,  125,    1,    2,   11,   12,   29,    1,
        2,    5,    6,    7,  124,   29,   11,   12,   37,   49,
       61,   73,    7,    7,    8,  123,   73,   37,   49,   61,
       77,  122,   81,    8,    8,    9,   89,    9,   94,    9,
       77,   81,   86,   99,   89,    9,   10,   94,   10,  108,
       10,  102,   86,   99,  114,  117,   10,   13,  108,  102,
      126,  128,  129,  117,  114,  130,   13,   13,   14,  118,
      126,  128,  129,  115,  131,  130,  132,   14,   14,   15,
      134,   15,  112,   15,  131,  133,  132,  135,  134,   15,
       16,  142,   16,  138,   16,  133,  146,  135,  156,  142,

       16,   17,  150,  138,  160,  105,  146,  159,  156,  161,
      150,   17,   17,   18,  160,  159,  162,  161,  103,  163,
      100,   97,   92,   18,   18,   19,  162,  163,   90,   87,
       84,   79,   75,   72,   19,   19,   19,   20,   65,   63,
       59,   58,   53,   46,   41,   34,   20,   20,   20,   21,
       32,   21,   27,   21,   26,   25,    4,    3,    0,   21,
       21,   22,    0,   22,    0,   22,    0,    0,    0,    0,
        0,   22,   22,   23,    0,    0,    0,    0,    0,    0,
       23,   23,   24,    0,    0,    0,    0,    0,    0,   24,
       24,   30,   30,    0,    0,    0,    0,   30,    0,    0,

        0,    0,   30,   42,    0,   42,    0,    0,    0,    0,
        0,    0,    0,   42,    0,   42,   43,    0,    0,    0,
       43,    0,    0,    0,    0,    0,   43,    0,   43,   54,
        0,   54,    0,    0,    0,    0,    0,    0,    0,   54,
        0,   54,   55,    0,    0,    0,   55,    0,    0,    0,
        0,    0,   55,    0,   55,   66,    0,   66,    0,    0,
        0,    0,    0,    0,    0,   66,   66,   66,   67,    0,
        0,    0,   67,    0,    0,    0,    0,    0,   67,   67,
       67,   71,    0,    0,    0,    0,    0,    0,   71,   71,
       85,    0,   85,    0,    0,    0,    0,    0,    0,    0,

       85,    0,   85,   88,    0,    0,    0,   88,    0,    0,
        0,    0,    0,   88,    0,   88,   98,    0,   98,    0,
        0,    0,    0,    0,    0,    0,   98,    0,   98,  101,
        0,    0,    0,  101,    0,    0,    0,    0,    0,  101,
        0,  101,  113,    0,  113,    0,    0,    0,    0,    0,
        0,    0,  113,  113,  113,  116,    0,    0,    0,  116,
        0,    0,    0,    0,    0,  116,  116,  116,  120,    0,
        0,    0,    0,    0,    0,  120,  120,  155,    0,  155,
        0,    0,    0,    0,    0,    0,    0,  155,    0,  155,
      158,    0,    0,    0,  158,    0,    0,    0,    0,    0,

      158,    0,  158,  165,  165,  165,  165,  165,  165,  165,
      165,  166,  166,  166,  166,  166,  166,  166,  166,  167,
      167,  167,  167,  167,  167,  167,  167,  168,  168,  168,
      168,  168,  168,  168,  168,  169,  169,  169,  169,  169,
      169,  169,  169,  170,  170,  170,  170,  170,  170,  170,
      170,  171,  171,  171,  171,  171,  171,  171,  171,  172,
      172,  172,  172,  172,  172,  172,  172,  173,  173,  173,
      173,  173,  173,  173,  173,  174,  174,  174,  174,  174,
      174,  174,  174,  175,  175,  175,  175,  175,  175,  175,
      175,  176,  176,  176,  176,  176,  176,  176,  176,  177,

      177,  177,  177,    0,  177,  177,  177,  178,  178,  178,
      178,    0,  178,  178,  178,  179,  179,    0,  179,  179,
      179,  179,  179,  180,    0,  180,  180,  180,  180,    0,
      180,  181,    0,  181,  181,  181,    0,    0,  181,  182,
        0,  182,  182,  182,  182,    0,  182,  183,  183,  183,
      183,  183,  183,  183,  183,  184,  184,  184,  184,  184,
      184,  184,  184,  185,    0,  185,  185,  185,  185,    0,
      185,  186,    0,  186,  186,  186,    0,    0,  186,  187,
        0,  187,  187,  187,  187,    0,  187,  188,  188,  188,
      188,  188,  188,  188,  188,  189,  189,  189,  189,  189,

      189,  189,  189,  190,    0,  190,  190,  190,  190,    0,
      190,  191,    0,  191,  191,  191,    0,    0,  191,  192,
        0,  192,  192,  192,  192,  193,  193,  193,  193,  193,
      193,  193,  193,  194,  194,  194,  194,  194,  194,  194,
      194,  195,    0,  195,  195,  196,  196,  196,  196,  196,
      196,    0,  196,  197,  197,  197,  197,  197,  197,  197,
      197,  198,  198,  198,  198,  198,  198,  198,  198,  199,
      199,  199,  199,  199,  199,  199,  199,  200,  200,  200,
      200,  200,  200,  200,  200,  201,  201,  201,  201,  201,
      201,  201,  201,  202,  202,  202,  202,  202,  202,  202,

      202,  203,    0,  203,  203,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "htmlop.l"
#define INITIAL 0
#line 2 "htmlop.l"

/* lhtml.l: source code for libhtmlparse parser
   Mooneer Salem <mooneer@translator.cx> 

   used and adapted for WebCleaner by
   Bastian Kleineidam <calvin@users.sourceforge.net>
   I ripped some of the code structure from sgmlop.c parser,
   which is written by Fredrik Lundh <fredrik@pythonware.com>
*/

#include <string.h>
/* tested with Python >= 2.0 only */
#include <Python.h>

#define LHTML_EOF -128
#define CFREE(a) PyMem_Del(a); a=NULL
#define PFREE(a) Py_DECREF(a); a=NULL
#define XCFREE(a) if (a) { PyMem_Del(a); a=NULL; }
#define XPFREE(a) if (a) { Py_DECREF(a); a=NULL; }
#define yyterminate() return YY_NULL
/* uncomment to debug
#define DEBUG
*/
#ifdef DEBUG
#define _debug fprintf(stderr, "state %d yytext %s\n", YYSTATE, yytext)
#else
#define _debug
#endif

int htmlopwrap (void) {
    return 1;
}

/* parser type definition */

typedef struct {
    PyObject_HEAD

    /* flex state */
    int state;
    
    /* temporary values for parsing */
    char* tag;
    char* paramname;
    PyObject* params;

    /* callbacks */
    PyObject* handle_starttag;
    PyObject* handle_endtag;
    PyObject* handle_decl;
    PyObject* handle_xmldecl;
    PyObject* handle_ref;
    PyObject* handle_data;
    PyObject* handle_comment;

} parser_object;

staticforward PyTypeObject parser_type;

/* pass the parser object to the scanner */
#define YY_DECL int html_scan (parser_object* self)

#define COMMENT 1

#define STARTTAG 2

#define PARAM 3

#define PARAM2 4

#define DECLTAG 5

#define DPARAM 6

#define DPARAM2 7

#define XMLTAG 8

#define XPARAM 9

#define XPARAM2 10

#define ENTITY 11

#define ENDTAG 12

#line 722 "htmlop.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 79 "htmlop.l"


#line 876 "htmlop.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 706 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case YY_STATE_EOF(INITIAL):
#line 81 "htmlop.l"
{
    _debug;
    return LHTML_EOF;
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 86 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_ref, "s", yytext+1);
    BEGIN(ENTITY);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 92 "htmlop.l"
{
    char *tmp = yytext + strlen(yytext) - 1;
    int i;
    _debug;
    for (i = strlen(tmp) - 1; i >= 0; i--) {
        if (*(tmp+i) != ';') {
	    unput(*(tmp+i));
	}
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 104 "htmlop.l"
{
    /* strip tag chars and whitespace */
    int i=2, j;
    _debug;
    while (*(yytext+i) != '\0' && isspace(*(yytext+i))) i++;
    j=i;
    while (*(yytext+j) != '\0' && !isspace(*(yytext+j))) j++;
    PyObject_CallFunction(self->handle_endtag, "s#", yytext+i, j-i);
    BEGIN(ENDTAG);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "htmlop.l"
{
    _debug;
    BEGIN(INITIAL);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 120 "htmlop.l"
{
    _debug;
    self->tag = PyMem_Resize(self->tag, char, 1);
    self->tag[0] = '\0';
    BEGIN(COMMENT);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 127 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(DECLTAG);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(STARTTAG);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 139 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(XMLTAG);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 145 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_data, "s", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_comment, "s", self->tag);
    CFREE(self->tag);
    BEGIN(INITIAL);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 157 "htmlop.l"
{
    int len = strlen(self->tag);
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len+strlen(yytext)] = '\0';
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 165 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    _debug;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 175 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 194 "htmlop.l"
{
    _debug;
    BEGIN(PARAM);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 199 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 225 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = PyMem_New(char, 1);
        self->paramname[0] = '\0';
    }
    BEGIN(PARAM2);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 235 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 242 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 20:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 256 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 262 "htmlop.l"
{
    int i=0;
    int j=strlen(yytext)-1;
    _debug;
    /* strip optional quotes, for things like <a b="c> */
    if (yytext[i]=='\'' || yytext[i]=='"') i++;
    if (yytext[j]=='\'' || yytext[j]=='"') j--;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+i, j-i+1));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 274 "htmlop.l"
{
    _debug;
    /* this occurs with <a b=> */
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 292 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 301 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 313 "htmlop.l"
{
    _debug;
    BEGIN(DPARAM);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 318 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 325 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 337 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = PyMem_New(char, 1);
        self->paramname[0] = '\0';
    }
    BEGIN(DPARAM2);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 347 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 354 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 361 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 368 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 374 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext, strlen(yytext)-1));
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 381 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    self->tag = PyMem_Resize(self->tag, char, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 390 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = PyMem_New(char, 1);
	self->tag[0] = '\0';
    }
    PyObject_CallFunction(self->handle_xmldecl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 402 "htmlop.l"
{
    _debug;
    BEGIN(XPARAM);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 407 "htmlop.l"
{
    _debug;
    self->paramname = PyMem_Resize(self->paramname, char, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 414 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    PyObject_CallFunction(self->handle_xmldecl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 426 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = PyMem_New(char, 1);
        self->paramname[0] = '\0';
    }
    BEGIN(XPARAM2);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 436 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 443 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 450 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 457 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 463 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext, strlen(yytext)-1));
    CFREE(self->paramname);
    BEGIN(XPARAM);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 470 "htmlop.l"
ECHO;
	YY_BREAK
#line 1520 "htmlop.c"
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(STARTTAG):
			case YY_STATE_EOF(PARAM):
			case YY_STATE_EOF(PARAM2):
			case YY_STATE_EOF(DECLTAG):
			case YY_STATE_EOF(DPARAM):
			case YY_STATE_EOF(DPARAM2):
			case YY_STATE_EOF(XMLTAG):
			case YY_STATE_EOF(XPARAM):
			case YY_STATE_EOF(XPARAM2):
			case YY_STATE_EOF(ENTITY):
			case YY_STATE_EOF(ENDTAG):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 164);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 470 "htmlop.l"


/* create parser */
static PyObject* htmlop_parser(PyObject* self, PyObject* args) {
    PyObject* item;
    parser_object* p;
    if (!PyArg_ParseTuple(args, "O", &item)) {
	return NULL;
    }

    if (!(p=PyObject_NEW(parser_object, &parser_type))) {
	return NULL;
    }

    p->state = 0;
    p->tag = NULL;
    p->paramname = NULL;
    p->params = NULL;

    /* register callbacks */
    p->handle_starttag = PyObject_GetAttrString(item, "handle_starttag");
    p->handle_endtag = PyObject_GetAttrString(item, "handle_endtag");
    p->handle_decl = PyObject_GetAttrString(item, "handle_decl");
    p->handle_xmldecl = PyObject_GetAttrString(item, "handle_xmldecl");
    p->handle_ref = PyObject_GetAttrString(item, "handle_ref");
    p->handle_data = PyObject_GetAttrString(item, "handle_data");
    p->handle_comment = PyObject_GetAttrString(item, "handle_comment");
    /* dont PyErr_Clear(); because we dont accept missing callbacks! */
    return (PyObject*) p;
}


static void parser_dealloc(parser_object* self)
{
    if (self->tag) {
       PyMem_Del(self->tag);
    }
    if (self->paramname) {
        PyMem_Del(self->paramname);
    }
    Py_XDECREF(self->params);
    Py_DECREF(self->handle_starttag);
    Py_DECREF(self->handle_endtag);
    Py_DECREF(self->handle_decl);
    Py_DECREF(self->handle_xmldecl);
    Py_DECREF(self->handle_ref);
    Py_DECREF(self->handle_data);
    Py_DECREF(self->handle_comment);
    PyMem_DEL(self);
}


static PyObject* parser_flush(parser_object* self, PyObject* args) {
    /* flush parser buffers */
    if (!PyArg_ParseTuple(args, "")) {
        return NULL;
    }
    /*
       Because we did not store previous data we have to look at 
       the current state and the temp vars.
    */
    switch(self->state) {
    case STARTTAG:
    case PARAM:
    case PARAM2:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        if (!self->params) {
            self->params = PyList_New(0);
        }
        if (self->tag[strlen(self->tag)-1]=='/') {
            /* no parameters allowed for this construct */
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
            PyObject_CallFunction(self->handle_endtag, "s", self->tag);
        }
        else {
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
        }
	break;
    case DECLTAG:
    case DPARAM:
    case DPARAM2:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
        break;
    case COMMENT:
        if (!self->tag) {
            self->tag = PyMem_New(char, 1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_comment, "s", self->tag);
	break;
    default:
        break;
    }
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_feed(parser_object* self, PyObject* args) {
    /* feed a chunk of data to the parser */
    char* s;
    int slen;
    YY_BUFFER_STATE bufstate;
    if (!PyArg_ParseTuple(args, "t#", &s, &slen)) {
	return NULL;
    }
    bufstate = htmlop_scan_bytes(s, slen);
    if (self->state != YYSTATE) {
        BEGIN(self->state);
    }
    html_scan(self);
    self->state = YYSTATE;
    htmlop_delete_buffer(bufstate);
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_reset(parser_object* self, PyObject* args) {
    if (!PyArg_ParseTuple(args, "")) {
	return NULL;
    }
    XCFREE(self->tag);
    XCFREE(self->paramname);
    XPFREE(self->params);
    self->state = INITIAL;
    Py_INCREF(Py_None);
    return Py_None;
}


/* type interface */

static PyMethodDef parser_methods[] = {
    /* incremental parsing */
    {"feed",  (PyCFunction) parser_feed, METH_VARARGS},
    /* reset the parser (no flushing) */
    {"reset", (PyCFunction) parser_reset, METH_VARARGS},
    /* flush the parser buffers */
    {"flush", (PyCFunction) parser_flush, METH_VARARGS},
    {NULL, NULL}
};


static PyObject* parser_getattr(parser_object* self, char* name) {
    return Py_FindMethod(parser_methods, (PyObject*) self, name);
}


statichere PyTypeObject parser_type = {
    PyObject_HEAD_INIT(NULL)
    0, /* ob_size */
    "parser", /* tp_name */
    sizeof(parser_object), /* tp_size */
    0, /* tp_itemsize */
    /* methods */
    (destructor)parser_dealloc, /* tp_dealloc */
    0, /* tp_print */
    (getattrfunc)parser_getattr, /* tp_getattr */
    0 /* tp_setattr */
};


/* python module interface */

static PyMethodDef htmlop_methods[] = {
    {"parser", htmlop_parser, METH_VARARGS},
    {NULL, NULL}
};


/* initialization of the htmlop module */

void inithtmlop(void) {
    Py_InitModule("htmlop", htmlop_methods);
}
