#define yy_create_buffer htmlop_create_buffer
#define yy_delete_buffer htmlop_delete_buffer
#define yy_scan_buffer htmlop_scan_buffer
#define yy_scan_string htmlop_scan_string
#define yy_scan_bytes htmlop_scan_bytes
#define yy_flex_debug htmlop_flex_debug
#define yy_init_buffer htmlop_init_buffer
#define yy_flush_buffer htmlop_flush_buffer
#define yy_load_buffer_state htmlop_load_buffer_state
#define yy_switch_to_buffer htmlop_switch_to_buffer
#define yyin htmlopin
#define yyleng htmlopleng
#define yylex htmloplex
#define yyout htmlopout
#define yyrestart htmloprestart
#define yytext htmloptext
#define yywrap htmlopwrap

#line 20 "htmlop.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
static yyconst short int yy_acclist[121] =
    {   0,
        8,    8,   35,    8,   34,    8,   34,    7,   34,   10,
       34,   10,   34,   11,   34,   13,   34,   12,   34,   14,
       34,   17,   34,   16,   34,   15,   34,   21,   34,   20,
       34,   21,   34,   21,   34,   22,   34,   23,   34,   25,
       34,   24,   34,   26,   34,   29,   34,   28,   34,   27,
       34,   33,   34,   32,   34,   33,   34,   33,   34,   34,
        2,   34,    4,   34,    8,    8,16385,    7,    6,   10,
       11,   13,   14,   17,   16,   21,   20,   21,   21,   21,
       21,   23,   25,   26,   29,   28,   33,   32,   33,   33,
       33,   33,    2, 8193,    8, 8193,    6,    9,   21,   21,

       21,   21,   30,   33,   30,   30,   33,   31,   33,   31,
       31,   33,    5,    3,   18,   18,   19,   19,   30,   31
    } ;

static yyconst short int yy_accept[122] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    6,    8,   10,   12,   14,   16,   18,   20,
       22,   24,   26,   28,   30,   32,   34,   36,   38,   40,
       42,   44,   46,   48,   50,   52,   54,   56,   58,   60,
       61,   63,   65,   66,   68,   69,   70,   70,   71,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   79,   80,
       81,   81,   82,   83,   84,   85,   86,   87,   88,   89,
       90,   90,   91,   92,   92,   93,   94,   96,   97,   98,
       98,   98,   98,   99,  100,  100,  100,  101,  102,  102,

      102,  103,  105,  106,  106,  108,  110,  111,  111,  113,
      114,  115,  116,  116,  117,  118,  118,  119,  120,  121,
      121
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    4,    1,    1,    1,    5,    6,    1,
        1,    1,    1,    1,    7,    1,    8,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       11,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   13,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[14] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    4,    5,
        6,    7,    1
    } ;

static yyconst short int yy_base[152] =
    {   0,
        0,    6,   30,   29,   15,   26,   37,   48,   59,   70,
       81,   92,  103,  114,  125,  136,  147,  156,   23,   22,
       33,    0,  165,  173,    0,   25,    0,   29,  709,    0,
      180,  709,  709,    0,   28,  190,  202,  709,    0,   27,
      709,    0,  214,  709,  709,    0,   24,  224,  236,  709,
        0,  709,    0,  248,   23,  257,    0,    0,  263,    0,
       22,    0,    0,  709,    0,   21,  274,  284,   18,  296,
      304,   15,    0,   18,    0,    0,  709,    0,   17,  316,
      326,   14,  338,  346,    9,    0,  358,    0,   12,    6,
        0,    0,  709,  367,    0,  376,  388,  399,    0,  406,

      418,    0,  709,  427,    0,    0,  709,  435,    0,  709,
      709,  709,  447,  457,  709,  469,  477,  487,  495,  709,
      508,  515,  522,  529,  536,  543,  550,  557,  564,  571,
      578,  585,  592,  598,  603,  609,  616,  623,  629,  634,
      640,  647,  653,  658,  664,  671,  678,  685,  691,  695,
      701
    } ;

static yyconst short int yy_def[152] =
    {   0,
      121,  121,  122,  122,  123,  123,  124,  124,  125,  125,
      126,  126,  127,  127,  128,  128,  129,  129,  129,  129,
      120,  130,  131,  120,  132,  120,  133,  120,  120,  134,
      120,  120,  120,  135,  120,  136,  137,  120,  138,  120,
      120,  139,  120,  120,  120,  140,  120,  141,  142,  120,
      143,  120,  130,  131,  120,  120,  144,  132,  120,  133,
      120,  134,   31,  120,  135,  120,  136,  145,   67,  137,
      146,   70,  138,  120,  139,   43,  120,  140,  120,  141,
      147,   80,  142,  148,   83,  143,  130,  149,  120,  120,
      144,   59,  120,  135,  150,  145,   67,  135,  151,  146,

       70,  140,  120,  147,   80,  140,  120,  148,   83,  120,
      120,  120,  145,  145,  120,  146,  146,  147,  148,    0,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120
    } ;

static yyconst short int yy_nxt[723] =
    {   0,
      120,  120,  120,  120,   23,  120,  120,  120,  120,   24,
       23,  111,  110,   89,  109,   24,   28,  105,   79,   74,
      101,   97,   66,   61,   55,   79,   29,   28,   74,   66,
       61,   59,  120,   52,   52,   26,   26,   29,   31,  120,
      120,  120,  120,  120,  120,  120,  120,   32,   33,   31,
      120,  120,  120,  120,  120,  120,  120,  120,   32,   33,
       35,  120,   36,  120,   37,  120,  120,  120,  120,  120,
       38,   35,  120,   36,  120,   37,  120,  120,  120,  120,
      120,   38,   40,  120,  120,  120,  120,  120,  120,  120,
      120,  120,   41,   40,  120,  120,  120,  120,  120,  120,

      120,  120,  120,   41,   43,  120,  120,  120,  120,  120,
      120,  120,  120,   44,   45,   43,  120,  120,  120,  120,
      120,  120,  120,  120,   44,   45,   47,  120,   48,  120,
       49,  120,  120,  120,  120,  120,   50,   47,  120,   48,
      120,   49,  120,  120,  120,  120,  120,   50,   51,  120,
      120,  120,  120,  120,  120,   51,   51,   51,  120,  120,
      120,  120,  120,  120,   51,   51,   53,  120,  120,  120,
      120,  120,  120,   53,   55,   56,  120,  120,  120,  120,
       57,   63,  120,  120,  120,  120,  120,  120,  120,  120,
       64,   68,  120,   65,  120,  120,  120,  120,  120,  120,

      120,   68,   69,   71,  120,  120,  120,   65,  120,  120,
      120,  120,  120,   71,   72,   76,  120,  120,  120,  120,
      120,  120,  120,  120,   77,   81,  120,   78,  120,  120,
      120,  120,  120,  120,  120,   81,   82,   84,  120,  120,
      120,   78,  120,  120,  120,  120,  120,   84,   85,   87,
      120,  120,  120,  120,  120,  120,   87,   88,   89,  120,
      120,  120,  120,   90,   92,  120,  120,  120,  120,  120,
      120,  120,  120,  120,   93,   68,  120,   94,  120,  120,
      120,  120,  120,  120,  120,   68,   69,   95,  120,  120,
      120,  120,  120,  120,  120,  120,   96,   71,  120,  120,

      120,   98,  120,  120,  120,  120,  120,   71,   72,   99,
      120,  120,  120,  120,  120,  120,  100,   81,  120,  102,
      120,  120,  120,  120,  120,  120,  120,   81,   82,  103,
      120,  120,  120,  120,  120,  120,  120,  120,  104,   84,
      120,  120,  120,  106,  120,  120,  120,  120,  120,   84,
       85,  107,  120,  120,  120,  120,  120,  120,  108,   87,
      120,  120,  120,  120,  120,  120,   87,   88,  112,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  112,  113,
      120,  120,  120,  120,  120,  120,  120,  120,   96,  114,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  114,

      115,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      115,  116,  120,  120,  120,  120,  120,  120,  100,  117,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  117,
      118,  120,  120,  120,  120,  120,  120,  120,  120,  104,
      119,  120,  120,  120,  120,  120,  120,  108,  114,  120,
       95,  120,  120,  120,  120,  120,  120,  120,  114,   96,
       95,  120,  120,  120,  120,  120,  120,  120,  120,   96,
      117,  120,  120,  120,   99,  120,  120,  120,  120,  120,
      117,  100,   99,  120,  120,  120,  120,  120,  120,  100,
      103,  120,  120,  120,  120,  120,  120,  120,  120,  104,

      107,  120,  120,  120,  120,  120,  120,  108,   22,   22,
       22,   22,   22,   22,   22,   25,   25,   25,   25,   25,
       25,   25,   27,   27,   27,   27,   27,   27,   27,   30,
       30,   30,   30,   30,   30,   30,   34,   34,   34,   34,
       34,   34,   34,   39,   39,   39,   39,   39,   39,   39,
       42,   42,   42,   42,   42,   42,   42,   46,   46,   46,
       46,   46,   46,   46,   50,   50,   50,   50,   50,   50,
       50,   53,   53,   53,   53,  120,   53,   53,   54,   54,
       54,   54,  120,   54,   54,   58,   58,  120,   58,   58,
       58,   58,   60,  120,   60,   60,   60,   60,   62,  120,

       62,   62,   62,   65,  120,   65,   65,   65,   65,   67,
       67,   67,   67,   67,   67,   67,   70,   70,   70,   70,
       70,   70,   70,   73,  120,   73,   73,   73,   73,   75,
      120,   75,   75,   75,   78,  120,   78,   78,   78,   78,
       80,   80,   80,   80,   80,   80,   80,   83,   83,   83,
       83,   83,   83,   83,   86,  120,   86,   86,   91,   91,
       91,   91,   91,   91,   68,   68,   68,   68,   68,   68,
       68,   71,   71,   71,   71,   71,   71,   71,   81,   81,
       81,   81,   81,   81,   81,   84,   84,   84,   84,   84,
       84,   84,   88,  120,   88,   88,  112,  120,  120,  120,

      120,  112,  115,  120,  120,  120,  120,  115,   21,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

static yyconst short int yy_chk[723] =
    {   0,
        0,    0,    0,    0,    1,    0,    0,    0,    0,    1,
        2,   91,   90,   89,   85,    2,    5,   82,   79,   74,
       72,   69,   66,   61,   55,   47,    5,    6,   40,   35,
       28,   26,   21,   20,   19,    4,    3,    6,    7,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    7,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    8,    8,
        9,    0,    9,    0,    9,    0,    0,    0,    0,    0,
        9,   10,    0,   10,    0,   10,    0,    0,    0,    0,
        0,   10,   11,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   11,   12,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   12,   13,    0,    0,    0,    0,    0,
        0,    0,    0,   13,   13,   14,    0,    0,    0,    0,
        0,    0,    0,    0,   14,   14,   15,    0,   15,    0,
       15,    0,    0,    0,    0,    0,   15,   16,    0,   16,
        0,   16,    0,    0,    0,    0,    0,   16,   17,    0,
        0,    0,    0,    0,    0,   17,   17,   18,    0,    0,
        0,    0,    0,    0,   18,   18,   23,    0,    0,    0,
        0,    0,    0,   23,   24,   24,    0,    0,    0,    0,
       24,   31,    0,    0,    0,    0,    0,    0,    0,    0,
       31,   36,    0,   36,    0,    0,    0,    0,    0,    0,

        0,   36,   36,   37,    0,    0,    0,   37,    0,    0,
        0,    0,    0,   37,   37,   43,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   48,    0,   48,    0,    0,
        0,    0,    0,    0,    0,   48,   48,   49,    0,    0,
        0,   49,    0,    0,    0,    0,    0,   49,   49,   54,
        0,    0,    0,    0,    0,    0,   54,   54,   56,    0,
        0,    0,    0,   56,   59,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,   67,    0,   67,    0,    0,
        0,    0,    0,    0,    0,   67,   67,   68,    0,    0,
        0,    0,    0,    0,    0,    0,   68,   70,    0,    0,

        0,   70,    0,    0,    0,    0,    0,   70,   70,   71,
        0,    0,    0,    0,    0,    0,   71,   80,    0,   80,
        0,    0,    0,    0,    0,    0,    0,   80,   80,   81,
        0,    0,    0,    0,    0,    0,    0,    0,   81,   83,
        0,    0,    0,   83,    0,    0,    0,    0,    0,   83,
       83,   84,    0,    0,    0,    0,    0,    0,   84,   87,
        0,    0,    0,    0,    0,    0,   87,   87,   94,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   94,   96,
        0,    0,    0,    0,    0,    0,    0,    0,   96,   97,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   97,

       98,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       98,  100,    0,    0,    0,    0,    0,    0,  100,  101,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  101,
      104,    0,    0,    0,    0,    0,    0,    0,    0,  104,
      108,    0,    0,    0,    0,    0,    0,  108,  113,    0,
      113,    0,    0,    0,    0,    0,    0,    0,  113,  113,
      114,    0,    0,    0,    0,    0,    0,    0,    0,  114,
      116,    0,    0,    0,  116,    0,    0,    0,    0,    0,
      116,  116,  117,    0,    0,    0,    0,    0,    0,  117,
      118,    0,    0,    0,    0,    0,    0,    0,    0,  118,

      119,    0,    0,    0,    0,    0,    0,  119,  121,  121,
      121,  121,  121,  121,  121,  122,  122,  122,  122,  122,
      122,  122,  123,  123,  123,  123,  123,  123,  123,  124,
      124,  124,  124,  124,  124,  124,  125,  125,  125,  125,
      125,  125,  125,  126,  126,  126,  126,  126,  126,  126,
      127,  127,  127,  127,  127,  127,  127,  128,  128,  128,
      128,  128,  128,  128,  129,  129,  129,  129,  129,  129,
      129,  130,  130,  130,  130,    0,  130,  130,  131,  131,
      131,  131,    0,  131,  131,  132,  132,    0,  132,  132,
      132,  132,  133,    0,  133,  133,  133,  133,  134,    0,

      134,  134,  134,  135,    0,  135,  135,  135,  135,  136,
      136,  136,  136,  136,  136,  136,  137,  137,  137,  137,
      137,  137,  137,  138,    0,  138,  138,  138,  138,  139,
        0,  139,  139,  139,  140,    0,  140,  140,  140,  140,
      141,  141,  141,  141,  141,  141,  141,  142,  142,  142,
      142,  142,  142,  142,  143,    0,  143,  143,  144,  144,
      144,  144,  144,  144,  145,  145,  145,  145,  145,  145,
      145,  146,  146,  146,  146,  146,  146,  146,  147,  147,
      147,  147,  147,  147,  147,  148,  148,  148,  148,  148,
      148,  148,  149,    0,  149,  149,  150,    0,    0,    0,

        0,  150,  151,    0,    0,    0,    0,  151,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "htmlop.l"
#define INITIAL 0
#line 2 "htmlop.l"

/* lhtml.l: source code for libhtmlparse parser
   Mooneer Salem <mooneer@translator.cx> 

   used and adapted for WebCleaner by
   Bastian Kleineidam <calvin@users.sourceforge.net>
   I ripped some of the code structure from sgmlop.c parser,
   which is written by Fredrik Lundh <fredrik@pythonware.com>
*/

#include <string.h>
/* tested with Python >= 2.0 only */
#include <Python.h>

#define LHTML_EOF -128
#define CFREE(a) free(a); a=NULL
#define PFREE(a) Py_DECREF(a); a=NULL
#define XCFREE(a) if (a) { free(a); a=NULL; }
#define XPFREE(a) if (a) { Py_DECREF(a); a=NULL; }
#define yyterminate() return YY_NULL
/* uncomment to debug
#define DEBUG
*/
#ifdef DEBUG
#define _debug fprintf(stderr, "state %d yytext %s\n", YYSTATE, yytext)
#else
#define _debug
#endif

int htmlopwrap (void) {
    return 1;
}

/* parser type definition */

typedef struct {
    PyObject_HEAD

    /* flex state */
    int state;
    
    /* temporary values for parsing */
    char* tag;
    char* paramname;
    PyObject* params;

    /* callbacks */
    PyObject* handle_starttag;
    PyObject* handle_endtag;
    PyObject* handle_decl;
    PyObject* handle_xmldecl;
    PyObject* handle_ref;
    PyObject* handle_data;
    PyObject* handle_comment;

} parser_object;

staticforward PyTypeObject parser_type;

/* pass the parser object to the scanner */
#define YY_DECL int html_scan (parser_object* self)

#define COMMENT 1

#define STARTTAG 2

#define PARAM 3

#define PARAM2 4

#define DECLTAG 5

#define DPARAM 6

#define DPARAM2 7

#define ENTITY 8

#define ENDTAG 9

#line 697 "htmlop.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 76 "htmlop.l"


#line 851 "htmlop.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 121 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 709 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case YY_STATE_EOF(INITIAL):
#line 78 "htmlop.l"
{
    _debug;
    return LHTML_EOF;
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 83 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_ref, "s", yytext+1);
    BEGIN(ENTITY);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "htmlop.l"
{
    char *tmp = yytext + strlen(yytext) - 1;
    int i;
    _debug;
    for (i = strlen(tmp) - 1; i >= 0; i--) {
        if (*(tmp+i) != ';') {
	    unput(*(tmp+i));
	}
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 101 "htmlop.l"
{
    /* strip tag chars and whitespace */
    int i=2, j;
    _debug;
    while (*(yytext+i) != '\0' && isspace(*(yytext+i))) i++;
    j=i;
    while (*(yytext+j) != '\0' && !isspace(*(yytext+j))) j++;
    PyObject_CallFunction(self->handle_endtag, "s#", yytext+i, j-i);
    BEGIN(ENDTAG);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "htmlop.l"
{
    _debug;
    BEGIN(INITIAL);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "htmlop.l"
{
    _debug;
    self->tag = (char*) realloc(self->tag, 1);
    self->tag[0] = '\0';
    BEGIN(COMMENT);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(DECLTAG);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 130 "htmlop.l"
{
    _debug;
    self->params = PyList_New(0);
    BEGIN(STARTTAG);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_data, "s", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 141 "htmlop.l"
{
    _debug;
    PyObject_CallFunction(self->handle_comment, "s", self->tag);
    CFREE(self->tag);
    BEGIN(INITIAL);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 148 "htmlop.l"
{
    int len = strlen(self->tag);
    _debug;
    self->tag = (char*) realloc(self->tag, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len+strlen(yytext)] = '\0';
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 156 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    _debug;
    self->tag = (char*) realloc(self->tag, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 166 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = (char*) malloc(1);
	self->tag[0] = '\0';
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 185 "htmlop.l"
{
    _debug;
    BEGIN(PARAM);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 190 "htmlop.l"
{
    _debug;
    self->paramname = (char*) realloc(self->paramname, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 197 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 216 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = (char*) malloc(1);
        self->paramname[0] = '\0';
    }
    BEGIN(PARAM2);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 226 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 18:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 233 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 240 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 247 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 253 "htmlop.l"
{
    int i=0;
    int j=strlen(yytext)-1;
    _debug;
    /* strip optional quotes, for things like <a b="c> */
    if (yytext[i]=='\'' || yytext[i]=='"') i++;
    if (yytext[j]=='\'' || yytext[j]=='"') j--;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+i, j-i+1));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 265 "htmlop.l"
{
    _debug;
    /* this occurs with <a b=> */
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    if (self->tag[strlen(self->tag)-1]=='/') {
        /* no parameters allowed for this construct */
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
	PyObject_CallFunction(self->handle_endtag, "s", self->tag);
    }
    else {
        PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
    }
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 283 "htmlop.l"
{
    char* tmp;
    int len = self->tag ? strlen(self->tag) : 0;
    self->tag = (char*) realloc(self->tag, len + strlen(yytext) + 1);
    strncpy(self->tag + len, yytext, strlen(yytext));
    self->tag[len + strlen(yytext)] = '\0';
    tmp = self->tag;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 292 "htmlop.l"
{
    _debug;
    if (!self->tag) {
        self->tag = (char*) malloc(1);
	self->tag[0] = '\0';
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 304 "htmlop.l"
{
    _debug;
    BEGIN(DPARAM);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 309 "htmlop.l"
{
    _debug;
    self->paramname = (char*) realloc(self->paramname, strlen(yytext)+1);
    strncpy(self->paramname, yytext, strlen(yytext));
    self->paramname[strlen(yytext)] = '\0';
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 316 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
	CFREE(self->paramname);
    }
    PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
    CFREE(self->tag);
    PFREE(self->params);
    BEGIN(INITIAL);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 328 "htmlop.l"
{
    _debug;
    if (!self->paramname) {
        /* the empty param name as default, for things like <a =1 =2> */
        self->paramname = (char*) malloc(1);
        self->paramname[0] = '\0';
    }
    BEGIN(DPARAM2);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 338 "htmlop.l"
{
    _debug;
    if (self->paramname) {
        PyList_Append(self->params, Py_BuildValue("sO", self->paramname, Py_None));
    }
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 345 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 352 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext+1, strlen(yytext)-2));
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 359 "htmlop.l"
{
    _debug;
    CFREE(self->paramname);
    BEGIN(DPARAM);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 365 "htmlop.l"
{
    _debug;
    PyList_Append(self->params, Py_BuildValue("ss#", self->paramname, yytext, strlen(yytext)-1));
    CFREE(self->paramname);
    BEGIN(PARAM);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 372 "htmlop.l"
ECHO;
	YY_BREAK
#line 1364 "htmlop.c"
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(STARTTAG):
			case YY_STATE_EOF(PARAM):
			case YY_STATE_EOF(PARAM2):
			case YY_STATE_EOF(DECLTAG):
			case YY_STATE_EOF(DPARAM):
			case YY_STATE_EOF(DPARAM2):
			case YY_STATE_EOF(ENTITY):
			case YY_STATE_EOF(ENDTAG):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 121 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 121 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 120);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 372 "htmlop.l"


/* create parser */
static PyObject* htmlop_parser(PyObject* self, PyObject* args) {
    PyObject* item;
    parser_object* p;
    if (!PyArg_ParseTuple(args, "O", &item)) {
	return NULL;
    }

    if (!(p=PyObject_NEW(parser_object, &parser_type))) {
	return NULL;
    }

    p->state = 0;
    p->tag = NULL;
    p->paramname = NULL;
    p->params = NULL;

    /* register callbacks */
    p->handle_starttag = PyObject_GetAttrString(item, "handle_starttag");
    p->handle_endtag = PyObject_GetAttrString(item, "handle_endtag");
    p->handle_decl = PyObject_GetAttrString(item, "handle_decl");
    p->handle_xmldecl = PyObject_GetAttrString(item, "handle_xmldecl");
    p->handle_ref = PyObject_GetAttrString(item, "handle_ref");
    p->handle_data = PyObject_GetAttrString(item, "handle_data");
    p->handle_comment = PyObject_GetAttrString(item, "handle_comment");
    /* dont PyErr_Clear(); because we dont accept missing callbacks! */
    return (PyObject*) p;
}


static void parser_dealloc(parser_object* self)
{
    if (self->tag) {
       free(self->tag);
    }
    if (self->paramname) {
        free(self->paramname);
    }
    Py_XDECREF(self->params);
    Py_DECREF(self->handle_starttag);
    Py_DECREF(self->handle_endtag);
    Py_DECREF(self->handle_decl);
    Py_DECREF(self->handle_xmldecl);
    Py_DECREF(self->handle_ref);
    Py_DECREF(self->handle_data);
    Py_DECREF(self->handle_comment);
    PyMem_DEL(self);
}


static PyObject* parser_flush(parser_object* self, PyObject* args) {
    /* flush parser buffers */
    if (!PyArg_ParseTuple(args, "")) {
        return NULL;
    }
    /*
       Because we did not store previous data we have to look at 
       the current state and the temp vars.
    */
    switch(self->state) {
    case STARTTAG:
    case PARAM:
    case PARAM2:
        if (!self->tag) {
            self->tag = (char*) malloc(1);
	    self->tag[0] = '\0';
        }
        if (!self->params) {
            self->params = PyList_New(0);
        }
        if (self->tag[strlen(self->tag)-1]=='/') {
            /* no parameters allowed for this construct */
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, PyList_New(0));
            PyObject_CallFunction(self->handle_endtag, "s", self->tag);
        }
        else {
            PyObject_CallFunction(self->handle_starttag, "sO", self->tag, self->params);
        }
	break;
    case DECLTAG:
    case DPARAM:
    case DPARAM2:
        if (!self->tag) {
            self->tag = (char*) malloc(1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_decl, "sO", self->tag, self->params);
        break;
    case COMMENT:
        if (!self->tag) {
            self->tag = (char*) malloc(1);
	    self->tag[0] = '\0';
        }
        PyObject_CallFunction(self->handle_comment, "s", self->tag);
	break;
    default:
        break;
    }
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_feed(parser_object* self, PyObject* args) {
    /* feed a chunk of data to the parser */
    char* s;
    int slen;
    YY_BUFFER_STATE bufstate;
    if (!PyArg_ParseTuple(args, "t#", &s, &slen)) {
	return NULL;
    }
    bufstate = htmlop_scan_bytes(s, slen);
    if (self->state != YYSTATE) {
        BEGIN(self->state);
    }
    html_scan(self);
    self->state = YYSTATE;
    htmlop_delete_buffer(bufstate);
    Py_INCREF(Py_None);
    return Py_None;
}


static PyObject* parser_reset(parser_object* self, PyObject* args) {
    if (!PyArg_ParseTuple(args, "")) {
	return NULL;
    }
    XCFREE(self->tag);
    XCFREE(self->paramname);
    XPFREE(self->params);
    Py_INCREF(Py_None);
    self->state = INITIAL;
    return Py_None;
}


/* type interface */

static PyMethodDef parser_methods[] = {
    /* incremental parsing */
    {"feed",  (PyCFunction) parser_feed, METH_VARARGS},
    /* reset the parser (no flushing) */
    {"reset", (PyCFunction) parser_reset, METH_VARARGS},
    /* flush the parser buffers */
    {"flush", (PyCFunction) parser_flush, METH_VARARGS},
    {NULL, NULL}
};


static PyObject* parser_getattr(parser_object* self, char* name) {
    return Py_FindMethod(parser_methods, (PyObject*) self, name);
}


statichere PyTypeObject parser_type = {
    PyObject_HEAD_INIT(NULL)
    0, /* ob_size */
    "parser", /* tp_name */
    sizeof(parser_object), /* tp_size */
    0, /* tp_itemsize */
    /* methods */
    (destructor)parser_dealloc, /* tp_dealloc */
    0, /* tp_print */
    (getattrfunc)parser_getattr, /* tp_getattr */
    0 /* tp_setattr */
};


/* python module interface */

static PyMethodDef htmlop_methods[] = {
    {"parser", htmlop_parser, METH_VARARGS},
    {NULL, NULL}
};


/* initialization of the htmlop module */

void inithtmlop(void) {
    Py_InitModule("htmlop", htmlop_methods);
}
