#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

package=webcleaner

STATE=1 
while [ "$STATE" != 0 -a "$STATE" != 3 ]; do
    case "$STATE" in
    1)
        db_input medium $package/port || true
        ;;
    2)
        db_input high $package/adminpass || true
        ;;
    esac
    if db_go; then
        if [ "$STATE"!="2" -o -n "$RES" ]; then
            STATE=$(($STATE + 1))
        fi
    else
        STATE=$(($STATE - 1))
    fi
done
