#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

package=webcleaner

db_input medium $package/port || true
db_input medium $package/monitor || true
db_input low $package/note || true
db_input high $package/password || true
db_go || true
