.TH WEBCLEANER\-CTL 1 "29. November 2004"
.SH NAME
webcleaner\-ctl - WebCleaner Proxy Kontrollschnittstelle
.SH SYNTAX
\fBwebcleaner\-ctl\fP \fIKommando\fP
.SH BESCHREIBUNG
\fBwebcleaner\-ctl\fP ist ein Kontrollwerkzeug für den WebCleaner Proxy.
Es ist vorhanden, um dem Administrator zu helfen, das Funktionieren des
Proxy Dämons sicherzustellen.

Das webcleaner\-ctl Skript gibt einen Rückgabewert von 0 bei Erfolg
zurück, und >0 falls ein Fehler auftritt. Für mehr Info betrachten
Sie die Kommentare im Skript.
.SH KOMMANDOS
.TP
\fBstart\fP
Falls der WebCleaner Proxy nicht läuft, starte ihn. Falls er stoppt,
starte ihn neu.
.TP
\fBstop\fP
Stoppe den WebCleaner Proxy.
.TP
\fBreload\fP
Lade die WebCleaner Proxy Konfiguration neu.
.TP
\fBstatus\fP
Gebe den Status des WebCleaner Proxies aus.
.SH "SIEHE AUCH"
webcleaner(1) runsvctrl(8) runsvstat(8) svwaitdown(8)
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
