#!/bin/sh -e
# prerm script for webcleaner
#
# see: dh_installdeb(1)

if [ "$1" = "remove" -o "$1" = "purge" ]; then
    # stop service
    webcleaner-ctl stop
    # remove service link
    if [ -h /var/service/webcleaner ]; then
        rm -f /var/service/webcleaner
    fi
    # remove SSL certificates
    webcleaner-certificates remove
fi

dpkg -L webcleaner |
	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
	xargs rm -f >&2

#DEBHELPER#

exit 0
