#!/bin/sh -e
# prerm script for webcleaner
#
# see: dh_installdeb(1)

package=webcleaner
service=/var/service/$package

if [ "$1" = "remove" ]; then
    # stop service
    svwaitdown $service
    # remove service link
    if [ -h /var/service/webcleaner ]; then
        rm -f /var/service/webcleaner
    fi
    # remove SSL certificates
    webcleaner-certificates remove
fi

dpkg -L $package |
	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
	xargs rm -f >&2

#DEBHELPER#

exit 0
