.TH WEBCLEANER 1 "6 December 2000"
.SH NAME
webcleaner - a filtering HTTP proxy
.SH SYNOPSIS
\fBwebcleaner\fP [\fIoptions\fP]
.SH DESCRIPTION
WebCleaner is a filtering HTTP proxy. You can encode, decode and modify
each part of an HTTP request. WebCleaner enhances your privacy and
efficiency on the web. It comes with several ready-to-use
filters to remove advertisement and unwanted HTML content,
compresses documents on-the-fly, disables animated GIF images and more.
.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print help text.
.TP
\fB\-d\fP \fIdirectory\fP, \fB\-\-configdir=\fP\fIdirectory\fP
Use given directory for configuration. It should include a
\fBwebcleaner.conf\fP file and several .zap files.
.TP
\fB\-\-no\-file\-logs\fP
Log to stdout instead of generating log files.
.SH CONFIGURATION
To configure WebCleaner, point your favourite webbrowser to
\fBhttp://localhost:\fP\fIport\fP\fB/\fP
where \fIport\fP is your configured WebCleaner port number
(default 8080).

The underlying configuration format is a custom XML format which
is explained in \fIwebcleaner.conf(5)\fP.
.SH "SEE ALSO"
webcleaner.conf(5)
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
.SH COPYRIGHT
Copyright \(co 2000-2005 Bastian Kleineidam
