.TH webcleaner\-certificates 1 2004-03-22 "WebCleaner"
.SH NAME
webcleaner\-certificates - generate or remove WebCleaner SSL certificates
.SH SYNOPSIS
\fBwebcleaner\-certificates\fP [\fIoptions\fP] \fIcommand\fP
.SH OPTIONS
.TP
\fB-d\fP \fIdirectory\fP, \fB\-\-configdir=\fP\fIdirectory\fP
Generate certificates in given directory instead of the
default one for WebCleaner.
See also the option \fB\-d\fP in \fBwebcleaner(1)\fP.
.SH COMMANDS
.TP
\fBinstall\fP
Generate and install WebCleaner SSL certificates for client and server
authentification.
If the certificates exist already, do nothing.
.TP
\fBremove\fP
Remove all previously generated WebCleaner SSL certificates.
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
.SH COPYRIGHT
Copyright \(co 2000-2008 Bastian Kleineidam
